# Generated by Django 5.2.1 on 2025-05-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject (for Email)')),
                ('body_html', models.TextField(blank=True, help_text='HTML content for email messages.', verbose_name='HTML Body (for Email)')),
                ('body_text', models.TextField(help_text='Plain text content for SMS, WhatsApp, and email fallback.', verbose_name='Text Body (for SMS/WhatsApp/Email Fallback)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=10, verbose_name='Status')),
                ('sent_to_report', models.TextField(blank=True, help_text='Log of sending attempts and outcomes.', verbose_name='Sending Report')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='If set, the message will be sent around this time.', null=True, verbose_name='Scheduled At')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, help_text='Include country code, e.g., +14155552671', max_length=20, null=True, unique=True, verbose_name='Phone Number (SMS)')),
                ('whatsapp_number', models.CharField(blank=True, help_text="Include country code with 'whatsapp:' prefix, e.g., whatsapp:+14155552671", max_length=30, null=True, unique=True, verbose_name='WhatsApp Number')),
                ('subscribed_to_email', models.BooleanField(default=False, verbose_name='Subscribed to Email')),
                ('subscribed_to_sms', models.BooleanField(default=False, verbose_name='Subscribed to SMS')),
                ('subscribed_to_whatsapp', models.BooleanField(default=False, verbose_name='Subscribed to WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
